# Generated by Django 3.2.9 on 2022-06-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_0003_alter_profile_user_0003_auto_20220618_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variations',
            field=models.ManyToManyField(blank=True, to='app.Variation'),
        ),
    ]
