# Generated by Django 3.2.9 on 2022-08-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='variations',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='variations',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
